### PR TITLE
Add the guide to labels

### PR DESCRIPTION
**Pull request by mkuzak**
addressing issue #6

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Can a normal user assign labels to their own issue?

**Comment by mkuzak** [comment]
No, they cannot, I completly forgot about it. We will be adding the labels I will rephrase the PR

**Review by ChristinaLK — APPROVED** [review]
this looks good!

**Comment by kerchner** [comment]
I'm not able to push to mkuzak/carpentryconhome-proposals so I'm providing suggested edits (just to the issue labels section) at https://gist.github.com/kerchner/d2ae270ac9c811342092145e3fec77b1

**Comment by mkuzak** [comment]
thank you @kerchner I will integrate the changes
next time you can provide suggestions inline in the review then I can merge them into the PR

**Comment by mkuzak** [comment]
Changes added. I like it, much cleaner now, thank you @kerchner.
I will merge the PR. We can always add more changes with new PRs

**Pull request merged**
